<main class="container-fluid p-5 about">
    <section>
        <div class="row">
            <div class="col-lg-4 offset-lg-1 ">
                <img src="img/image_3.jpg" alt="">
            </div>
            <div class="col-lg-4 offset-lg-1 ">
                <h2>Notre mission</h2>
                <hr>
                <p>
                    Plus de 300 000 boutiques en ligne à travers le monde font confiance à la technologie PrestaShop. Nous nous sommes fixé pour mission de développer un logiciel e-commerce ultra-performant en utilisant des technologies open source innovantes. Forts de notre
                    communauté, nous proposons un logiciel qui permet à chacun de faire prospérer sa boutique en ligne. PrestaShop figure au palmarès 2016 des 5 000 entreprises privées européennes dotées d’une croissance rapide, établi par le magazine
                    Inc. PrestaShop a également remporté en 2016 le CMS Critic Award du meilleur logiciel e-commerce.
                </p>
            </div>
        </div>
    </section>
    <section class="section2">
        <h3 class="text-center mt-5">Équipe de direction</h3>
        <hr>
        <div class="row mt-5 imgdiv">
            <div class="col-lg-2 offset-lg-2"><img src="img/poster01.jpg" alt="">

            </div>
            <div class="col-lg-2 "><img src="img/poster02.jpg" alt=""></div>
            <div class="col-lg-2 "><img src="img/poster03.jpg" alt=""></div>
            <div class="col-lg-2 "><img src="img/poster04.jpg" alt=""></div>
        </div>
    </section>

</main>