        <div class="row">
            <section class="col-lg-8 p-4 py-4" id=" articles">
                <div class="bg-white container">
                    <div class="page-container">

                        <h1 class="l-heading">Lorem ipsum dolor sit amet consectetur.</h1>
                        <div class="meta">
                            <small>
                                <span><i class="far fa-clock"> 02 mars 2020 </i></span>
                                <span><i class="far fa-eye"> 120 vues </i></span>
                                <span><i class="far fa-comment"> 50 commentaires </i></span>
                            </small>
                            <hr>
                            <article class="cards">
                                <img src="img/showcase.jpg" alt="">
                        </div>
                        <br>
                        <p>praesentibus ne mandaremus quamquam expetendis illum possumus voluptatibus doctrina dolor se
                            graviterque culpa adipisicing occaecat firmissimum instituendarum tamen efflorescere culpa
                            nostrud incididunt nisi officia se mentitum ubi iis incurreret quid cillum consequat aliqua
                            commodo aliqua quem
                            efflorescere aut quibusdam si quem fidelissimae ut summis magna enim eu
                            praesentibus nostrud aliqua</p>
                        <p>tamen iis consequat quibusdam qui te culpa sempiternum dolor eu appellat irure
                            se familiaritatem incurreret occaecat appellat imitarentur duis do nulla dolor
                            enim eruditionem duis dolor reprehenderit imitarentur ad te litteris possumus
                            instituendarum enim nostrud voluptate eu magna ita quae cillum arbitrantur
                            labore ex fidelissimae consectetur arbitrantur quo quamquam arbitrantur
                            distinguantur officia familiaritatem ne graviterque admodum a varias vidisse
                            duis instituendarum dolore singulis sint exquisitaque ipsum singulis arbitror
                            consequat distinguantur illustriora aute irure quid sint ad ubi fore illum quae
                            elit legam e eu possumus ex hic ingeniis esse sint efflorescere mandaremus de
                            aliqua in summis veniam cillum magna do</p>
                        </article>
                    </div>
                </div>
                <div class="bg-white writer py-4 mt-5 col-lg-12 align-top">
                    <legend><i class="fa fa-user-edit"> Auteur</i> </legend>
                    <hr class="m-0 p-4">
                    <!---
                --><img class="col-4 col-sm-4 col-md-2 col-lg-2 col-xl-2 align-top " src="img/avatar.png" alt=""><!---
                --><div class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10 d-inline-block">
                        <p><strong>Jhon Doe</strong></p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quod minima enim sunt velit et
                            quam officia animi, eaque voluptatem pariatur soluta a inventore neque nemo dicta minus
                            tenetur. Deserunt ea iure in alias saepe quam similique pariatur.</p>
                    </div>
                </div>
                <div class="comments py-4 mt-2 col-lg-12 align-top">
                    <!---
                -->
                    <legend><i class="far fa-comments"> Les commentaires</i> </legend>
                    <hr class="m-0 p-4">
                    <div class="comment">
                        <img class= "col-2 col-sm-2 col-md-1 col-lg-1 col-xl-1 align-top" src="img/avatar.png" alt="">
                        <!---
                    -->
                        <div class="col-lg-9 col-xl-9 col-sm-12 d-inline-block">
                            <p class="mb-1"><strong>Jhon Doe</strong></p>
                            <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quod minima enim
                                    sunt velit et
                                    quam officia animi, eaque voluptatem pariatur soluta a inventore neque nemo dicta
                                    minus
                                    tenetur. Deserunt ea iure in alias saepe quam similique pariatur.</small></p><hr>
                        </div>
                        <div class="comment">
                            <img class= "col-2 col-sm-2 col-md-1 col-lg-1 col-xl-1 align-top" src="img/avatar.png" alt="">
                            <!---
                            -->
                            <div class="col-lg-9 col-xl-9 col-sm-12 d-inline-block">
                                <p class="mb-1"><strong>Jhon Doe</strong></p>
                                <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quod minima enim
                                        sunt velit et
                                        quam officia animi, eaque voluptatem pariatur soluta a inventore neque nemo
                                        dicta minus
                                        tenetur. Deserunt ea iure in alias saepe quam similique pariatur.</small></p><hr>
                            </div>
                            <div class="comment">
                                <img class="col-2 col-sm-2 col-md-1 col-lg-1 col-xl-1 align-top" src="img/avatar.png" alt=""><!---
                                    --><div class="col-lg-9 col-xl-9 col-sm-12 d-inline-block">
                                    <p class="mb-1"><strong>Jhon Doe</strong></p>
                                    <p><small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quod minima
                                            enim sunt velit et
                                            quam officia animi, eaque voluptatem pariatur soluta a inventore neque nemo
                                            dicta minus
                                            tenetur. Deserunt ea iure in alias saepe quam similique pariatur.</small>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="bg-white p-4 mt-5 align-top">
                            <fieldset class=" py-4 align-top">
                                <legend class=""><i class="far fa-comment"> Nouveau commentaire</i> </legend>
                                <hr class="m-0 p-4">
                                <ul>
                                    <li>
                                        <label class="col-lg-3  p-0" for="nickname">Pseudo :</label>
                                        <input class="col-lg-12" type="text" id="nickname" name="nickname">
                                    </li>
                                    <li>
                                        <label class="mt-2 col-lg-3 p-0" class="textarea" for="contents">Commentaire :</label>
                                        <textarea class="col-lg-12" name="contents" id="contents" rows="5"></textarea>
                                    </li>
                                    <li class="m-4 text-center">
                                        <button class="btn btn-warning" type="submit">Ajouter</button>
                                        <a class="btn btn-danger" href="index.php">Annuler</a>
                                    </li>
                                </ul>
                            </fieldset>
                        </div>

            </section>

            <aside class="col-lg-4 sidebar pl-lg-5">

                <div>
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <i class="icon icon-search"></i>
                                <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                            </div>
                        </form>

                    </div>
                    <div class="sidebar-box">
                        <div class="categories">
                            <h3>Categories</h3>
                            <li><a href="#">Sport <span class="ion-ios-arrow-forward"></span></a></li>
                            <li><a href="#">Politique <span class="ion-ios-arrow-forward"></span></a></li>
                            <li><a href="#">Santé <span class="ion-ios-arrow-forward"></span></a></li>
                            <li><a href="#">Education <span class="ion-ios-arrow-forward"></span></a></li>
                            <li><a href="#">Science <span class="ion-ios-arrow-forward"></span></a></li>
                        </div>
                    </div>
                    <div class="sidebar-box">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            <a href="#" class="tag-cloud-link">cat</a>
                            <a href="#" class="tag-cloud-link">abstract</a>
                            <a href="#" class="tag-cloud-link">people</a>
                            <a href="#" class="tag-cloud-link">person</a>
                            <a href="#" class="tag-cloud-link">model</a>
                            <a href="#" class="tag-cloud-link">delicious</a>
                            <a href="#" class="tag-cloud-link">desserts</a>
                            <a href="#" class="tag-cloud-link">drinks</a>
                        </div>

                    </div>
                    <div class="sidebar-box">
                        <h3>Time</h3>

                        <div id="MyClockDisplay" class="clock" onload="showTime()"></div>


                    </div>

                </div>

            </aside>
        </div>