
<div class="container-fluid contact">
    <h3 class="text-center">Informations de contact</h3>
    <div class="row my-5 text-center">
            <div class="col-lg-3 col-md-12 col-xs-12 bg-light p-2">
                <span class="font-weight-bold text-secondary">Website :</span><a href="#"> www.3w-dev-team.com</a>
            </div>
            <div class="col-lg-3 col-md-12 col-xs-12 bg-light p-2">
                <span class="font-weight-bold text-secondary">Email :</span><a href="mailto:3wdev@gmail.com"> 3w-dev@gmail.com</a>
            </div>
            <div class="col-lg-3 col-md-12 col-xs-12 bg-light p-2">
                <span class="font-weight-bold text-secondary">Adresse :</span> Tunis --Tunisie
            </div>
            <div class="col-lg-3 col-md-12 col-xs-12 bg-light p-2">
                <span class="font-weight-bold text-secondary">Tél :</span> +216 12 123 123
            </div>
    </div>
	<div class="row">
        <div class="col-lg-6 col-md-12 col-xs-12">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-xs-4">
                    <div class="contact-info text-center">
                        <img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image" class="w-50"/>
                        <h2>N'hésitez pas a nous Contactez</h2>
                        <h4>On veut connaitre vos idées et vos remarques!</h4>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-xs-12">
                    <div class="contact-form">
                        <div class="form-group">
                          <label class="control-label col-xs-2" for="fname">Nom:</label>
                          <div class="col-xs-10">          
                            <input type="text" class="form-control" id="fname" placeholder="Enter votre nom" name="fname">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-xs-2" for="lname">Prénom:</label>
                          <div class="col-xs-10">          
                            <input type="text" class="form-control" id="lname" placeholder="Enter votre prénom" name="lname">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-xs-2" for="email">Email:</label>
                          <div class="col-xs-10">
                            <input type="email" class="form-control" id="email" placeholder="Enter votre email" name="email">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-xs-2" for="comment">Message:</label>
                          <div class="col-xs-10">
                            <textarea class="form-control" rows="5" id="comment"></textarea>
                          </div>
                        </div>

                        <div class="form-group">      
                          <div class="col-lg-12 col-md-12 col-xs-12">
                            <button type="submit" class="btn btn-default w-100">Envoyer</button>
                          </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6 col-md-12 col-xs-12">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3194.53808862365!2d10.117504512228509!3d36.80562385477887!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2stn!4v1575498843413!5m2!1sfr!2stn"
            class="my-2 w-100 h-100"></iframe>
        </div>

	</div>
</div>
