<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0d242bcc89.js" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/article.css">
    <link rel="stylesheet" href="css/login.css">
    <link rel="stylesheet" href="css/contact.css">
    <link rel="stylesheet" href="css/about.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
        integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">


    <title>Blog3w</title>
</head>

<body>

    <header id="header-2">
        <div class="bg-noir">
            <nav id="navbar" class="navbar navbar-inverse navbar-fixed-top">
                <a href="index.php">
                    <h3 id="logo">Blog<span style="color: #FFD369;">3w</span></h3>
                </a>
                <ul class="nav navbar-nav">
                    <li class='navActive'>
                        <a class='principal' href="index.php">Accueil</a>
                    </li>
                    <li><a class='principal' href="about.php">A propos</a>
                    </li>
                    <li><a class='principal' href="contact.php">Contact</a></li>
                    <li><a class='principal' href="login.php">S'identifier</a></li>
                </ul>
                <div class="menu-wrap">
                    <input type="checkbox" class="toggler">
                    <div class="hamburger">
                        <div></div>
                    </div>
                    <div class="menu">
                        <div>
                            <div>
                                <ul>
                                    <li>
                                        <a class='principal' href="index.html">Accueil</a>
                                    </li>
                                    <li><a class='principal' href="about.html">A propos</a>
                                    </li>
                                    <li><a class='principal' href="contact.html">Contact</a></li>
                                    <li><a class='principal' href="login.html">S'identifier</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>

    <main class="container-fluid p-5">

        <?php 
        include $pageName;
        ?>

    </main>




    <!-- Hamza -->
    <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="logo"><a href="#">BLOG</a></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                            there live the blind texts.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"><i
                                            class="fab fa-twitter"></i></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"><i
                                            class="fab fa-facebook-f"></i></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"><i
                                            class="fab fa-instagram"></i></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Dernières Nouvelles</h2>
                        <div class="block-21 mb-4 d-flex">
                            <a class="img mr-4 rounded" style="background-image: url(images/image_1.jpg);"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a>
                                </h3>
                                <div class="meta">
                                    <div>
                                        <a href="#"></span> Oct. 16, 2019</a>
                                    </div>
                                    <div>
                                        <a href="#"></span> Admin</a>
                                    </div>
                                    <div>
                                        <a href="#"></span> 19</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="img mr-4 rounded" style="background-image: url(images/image_2.jpg);"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a>
                                </h3>
                                <div class="meta">
                                    <div>
                                        <a href="#"></span> Oct. 16, 2019</a>
                                    </div>
                                    <div>
                                        <a href="#"></span> Admin</a>
                                    </div>
                                    <div>
                                        <a href="#"></span> 19</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Information</h2>
                        <ul class="list-unstyled">
                            <li><a href="#index.php" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"><i
                                            class="fas fa-chevron-right"></i></span>Accueil</a></li>
                            <li><a href="#about.php" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"><i
                                            class="fas fa-chevron-right"></i></span>À propos</a></li>
                            <li><a href="#contact.php" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"><i
                                            class="fas fa-chevron-right"></i></span>Contact</a></li>
                            <li><a href="#login.php" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"><i
                                            class="fas fa-chevron-right"></i></span>S'identifier</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Vous avez des questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"><i class="fas fa-map-marker-alt"></i></span><span
                                        class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                                </li>
                                <li><a href="#"><span class="icon icon-phone"><i
                                                class="fas fa-phone-alt"></i></span><span class="text">+2 392 3929
                                            210</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"><i
                                                class="fas fa-envelope"></i></span><span
                                            class="text">info@yourdomain.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>

                        Copyright 2020 All rights reserved | This template is made with <i class="fas fa-heart"></i> by
                        Colorlib</a>

                    </p>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>