        <div id="main" class="container mt-0 pt-5 pb-5">
            <div class="card mx-auto border-0">
              <div class="card-header border-bottom-0 bg-transparent">
                <ul class="nav nav-tabs justify-content-center pt-4" id="pills-tab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active  text-form-color" id="pills-login-tab" data-toggle="pill" href="#pills-login" role="tab" aria-controls="pills-login"
                       aria-selected="true">Login</a>
                  </li>
          
                  <li class="nav-item">
                    <a class="nav-link text-form-color" id="pills-register-tab" data-toggle="pill" href="#pills-register" role="tab" aria-controls="pills-register"
                       aria-selected="false">Register</a>
                  </li>
                </ul>
              </div>
          
              <div class="card-body pb-4">
                <div class="tab-content" id="pills-tabContent">
                  <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="pills-login-tab">

                                <form action="login.php" method="post" name="form1">
                                <div class="form-group">
                                    <input type="email" name="email" class="form-control" id="email" placeholder="Email" required autofocus>
                                </div>
                    
                                <div class="form-group">
                                    <input type="password" name="password" class="form-control" id="password" id="password" placeholder="Password" required>
                                </div>
                    
                                <div class="custom-control custom-checkbox">
                                    <input class="custom-control-input" id="customCheck1" checked="" type="checkbox">
                                    <label class="custom-control-label" for="customCheck1">Check me out</label>
                                </div>
                    
                                <div class="text-center pt-4">
                                    <button type="submit" name="Submit" class="btn  btn-form-color">Login</button>
                                </div>
                    
                                <div class="text-center pt-2">
                                    <a class="btn btn-link text-form-color" href="#">Forgot Your Password?</a>
                                </div>
                                </form>
                  </div>
          
                  <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="pills-register-tab">
                      
                                <form action="register.php" method="post" name="form2">
                                <div class="form-group">
                                    <input type="text" name="username" id="name" class="form-control" placeholder="Username" required autofocus>
                                </div>
                                <div class="form-group">
                                    <input type="text" name="firstname" id="firstname" class="form-control" placeholder="Firstname" required autofocus>
                                </div>
                                <div class="form-group">
                                    <input type="text" name="lastname" id="lastname" class="form-control" placeholder="lastname" required autofocus>
                                </div>
                    
                                <div class="form-group">
                                    <input type="email" name="email" id="email" class="form-control" placeholder="Email" required>
                                </div>
                    
                                <div class="form-group">
                                    <input type="password" name="password" id="password" class="form-control" placeholder="Set a password" required>
                                </div>
                    
                    
                                <div class="text-center pt-2 pb-1">
                                    <button type="submit" name="Submit" class="btn btn-form-color">Register</button>
                                </div>
                                </form>
                  </div>
                </div>
              </div>
            </div>
          </div>

      

   